describe('E2E Tests - Transactions Filter', () => {
    it('Should log into application', () => {
        browser.url('http://zero.webappsecurity.com/')
        const loginButton = $('#signin_button')
        loginButton.waitForExist()
        loginButton.click()
        const formLogin = $('#login_form')
        formLogin.waitForExist()
        const loginUserField = $('#user_login')
        loginUserField.setValue('username')
        const loginPwdField = $('#user_password')
        loginPwdField.setValue('password')
        const submitLogin = $('input[type="submit"]')
        submitLogin.click()
        $('.nav-tabs').waitForExist()
    })

    it('Transaction filter should work', () => {
        const accountTab = $('#account_activity_tab')
        accountTab.click()
        const findTransactionsTab = $('#tabs > ul > li:nth-child(2) > a')
        findTransactionsTab.waitForExist()
        findTransactionsTab.click()
        const descriptionField = $('#aa_description')
        descriptionField.waitForExist()
        descriptionField.setValue('TRANSFER')
        const findButton = $('button[type="submit"]')
        findButton.click()
        $('#filtered_transactions_for_account').waitForExist()
        // const resultsMsg = $('.well')
        // expect(resultsMsg).toHaveText('No results.')
        expect($('#filtered_transactions_for_account > table')).toBeVisible()
        expect($('#filtered_transactions_for_account > table > tbody > tr:nth-child(1) > td:nth-child(2)'))
        .toHaveText('ONLINE TRANSFER REF #UKKSDRQG6L')
    })
});